### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by ilexius** [iquirino/NetStash#1]
Hi Igor, this project looks very interesting. Thanks for open sourcing this!

Does the transport support TLS yet? Or is this planned?

Would be amazing to use encrypted transport, so it can be used over a public network, including client and server certificate checking for authenticated connections.

Thanks a lot!

**Comment by ilexius** [comment]
We posted a $100 bounty for this, if anyone has time to implement TLS with certificate validation for both client and server:
https://www.bountysource.com/issues/84142483-tls-support

**Comment by iquirino** [comment]
Hello @ilexius !
Its a pleasure to know you wanted my solution!
I'll try to working on enable TLS on this project, okay?

Regards,
Igor Quirino

**Comment by iquirino** [comment]
Hello @ilexius !
Your requested feature is fully implemented.
Can you check if fills all your needs?
*Already published to the Nuget Repository

Feel free to suggests new features.

Thank you!
